#!/usr/bin/env python3
"""Archive a Claude Code session in one step.

Usage:
    # Most recent session, title auto-generated by Claude:
    python scripts/save_session.py

    # Specific session ID, title auto-generated:
    python scripts/save_session.py <session-id>

    # Provide title explicitly:
    python scripts/save_session.py --title "My session"

    # Specific JSONL file:
    python scripts/save_session.py --file ~/.claude/projects/.../session.jsonl

Steps performed:
  1. Locate the session JSONL file in ~/.claude/projects/
  2. Auto-generate a title via `claude -p` if --title is omitted
  3. Generate the HTML replay via `npx claude-replay`
  4. Copy the replay to replays/ and generate a summary in summaries/

Tip: run `/status` inside Claude Code to get the current session ID.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import add_conversation  # noqa: E402

CLAUDE_PROJECTS = Path.home() / ".claude" / "projects"

TITLE_PROMPT = (
    "Read this Claude Code session and reply with a concise title (5-8 words, no punctuation). "
    "The title should describe the main task or topic. Reply with the title only, nothing else.\n\n"
)


def find_latest_session() -> Path:
    sessions = sorted(
        CLAUDE_PROJECTS.glob("*/*.jsonl"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not sessions:
        raise FileNotFoundError(f"No session files found in {CLAUDE_PROJECTS}")
    return sessions[0]


def find_session_by_id(session_id: str) -> Path:
    matches = list(CLAUDE_PROJECTS.glob(f"*/{session_id}.jsonl"))
    if not matches:
        raise FileNotFoundError(f"Session not found: {session_id}")
    return matches[0]


def extract_text_from_jsonl(session_file: Path) -> str:
    """Parse the session JSONL and return readable conversation text."""
    lines = []
    for raw in session_file.read_text(encoding="utf-8").splitlines():
        raw = raw.strip()
        if not raw:
            continue
        try:
            entry = json.loads(raw)
        except json.JSONDecodeError:
            continue
        role = (entry.get("role") or entry.get("type") or "").upper()
        content = entry.get("content") or entry.get("message") or ""
        if isinstance(content, list):
            content = " ".join(
                b.get("text", "") for b in content
                if isinstance(b, dict) and b.get("type") == "text"
            )
        if role and str(content).strip():
            lines.append(f"[{role}]\n{str(content).strip()}")
    return "\n\n".join(lines)


def generate_title(session_file: Path) -> str:
    print("Generating title...")
    conversation_text = extract_text_from_jsonl(session_file)
    result = subprocess.run(
        ["claude", "-p", TITLE_PROMPT + conversation_text[:8000]],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        raise RuntimeError(f"claude CLI failed: {result.stderr.strip()}")
    return result.stdout.strip().strip('"').strip("'")


def generate_replay(session_file: Path, output_path: Path) -> None:
    result = subprocess.run(
        ["npx", "claude-replay", str(session_file), "-o", str(output_path)],
        capture_output=True,
        text=True,
        shell=sys.platform == "win32",
    )
    if result.returncode != 0:
        raise RuntimeError(f"claude-replay failed:\n{result.stderr.strip()}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("session_id", nargs="?", help="Session ID (default: most recent)")
    parser.add_argument("--file", dest="session_file", help="Path to session JSONL file directly")
    parser.add_argument("--title", default=None, help="Conversation title (default: auto-generated)")
    parser.add_argument("--date", default=str(date.today()), help="YYYY-MM-DD (default: today)")
    parser.add_argument("--no-summary", action="store_true", help="Skip summary generation")
    args = parser.parse_args()

    if args.session_file:
        session_file = Path(args.session_file).expanduser().resolve()
    elif args.session_id:
        session_file = find_session_by_id(args.session_id)
    else:
        session_file = find_latest_session()
        print(f"Using latest session: {session_file.name}")

    if not session_file.exists():
        print(f"Error: not found: {session_file}", file=sys.stderr)
        sys.exit(1)

    title = args.title or generate_title(session_file)
    print(f"Title: {title}")

    tmp_path = Path(tempfile.mktemp(suffix=".html"))
    try:
        print("Generating replay...")
        generate_replay(session_file, tmp_path)
        add_conversation.archive(tmp_path, title, args.date, args.no_summary)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


if __name__ == "__main__":
    main()
